### ISSUE TITLE
How to build an API in a day with the Laravel API Boilerplate

### ISSUE THREAD

**Issue by specialtactics** [sydphp/meetup-talks#47]
## Description
This is a mostly practical talk (1/3 slides 2/3 prac) about building APIs quickly in PHP using the Laravel API boilerplate (a github project of mine).

There are about 15m of slides to introduce the topic and give it some grounding. The rest of the talk is live coding + demo; showing how easy it is to use this boilerplate, and then a rundown of the key features.

This is around about the same talk as done at the Laravel April meetup. My idea is to iterate over it based on feedback. So I will take on feedback and comments from that talk and people beginning to use it, make various improvements and refinements before giving it again at SydPHP.

## Length
Total length of the talk is 60-70 minutes, depending on number of questions asked by audience. I would ask for a slot of 60 minutes at least, and if more time could be given, that's great - if not, that's ok.

## Timing
In order to have enough time to improve the demo, ideally I would do this talk at the July meeting - but could be later if needed (just not earlier).

## Misc
This talk has been proven to work well and the feedback so far as been very positive (in terms of how interesting the talk is). There is little risk since all the material is ready, and it will only be improved between now and then.

**Comment by Szasza** [comment]
Hi @specialtactics ,

First of all thank you for the talk submission, it is much appreciated. We will definitely add it to the appropriate meetup's schedule.

As for the 60 mins, it may be challenging given that there is planned to be another long talk, and lightning talks as well. One slot is usually reserved for the sponsor but in case there won't be anyone for that one, I don't see any problems with having just one 60-70min talk instead of two 30+45min ones.

I would like to ask for your patience for the next couple of weeks, I will try to clarify and finalise the above as soon as possible.

Thank you again!

**Comment by Szasza** [comment]
Hi @specialtactics ,

Thank you again for offering to talk, it is greatly appreciated.

@dkcwd and @nootanghimire will be the organisers for July's meetup, please feel free to reach out to them in case of quesions.
